workers_dev = true
name = "react-router-hono2"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
main = "./durable.js"
assets = { directory = "./build/client/" }

[vars]
TEST="Cloudflare Test"
REACT_ROUTER_PUBLIC_TEST1 = "React Router Public Test1"
REACT_ROUTER_PUBLIC_TEST2 = "React Router Public Test2"

[observability]
enabled = true

[[durable_objects.bindings]]
name = "DURABLE_OBJECT"
class_name = "DurableObject"

[[migrations]]
tag = "v1" 
new_classes = ["DurableObject"] 
